// <auto-generated />
// This file was automatically generated by the PetePocoGenerator
// 
// The following connection settings were used to generate this file
// 
//     Connection String: `Server=192.168.80.2\sepacq;Initial Catalog=B2SSecurity;user id=sa; password=**zapped**;`
//     Provider:               `SqlServer`

// <auto-generated />
namespace B2SSecurity.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using PetaPoco;

    public partial class Record<T> where T : new()
    {
        private Dictionary<string, bool> modifiedColumns = null;
        [Ignore]
        public Dictionary<string, bool> ModifiedColumns { get { return modifiedColumns; } }
        protected void MarkColumnModified(string column_name)
        {
            if (ModifiedColumns != null)
            {
                ModifiedColumns[column_name] = true;
            }
        }

        private void OnLoaded()
        {
            modifiedColumns = new Dictionary<string,bool>();
        }
    }

    [TableName("[dbo].[CfgChannelKeys]")]
    [PrimaryKey("ID")]
    [ExplicitColumns]
    public partial class CfgChannelKey
        : Record<CfgChannelKey>
    {
        [Column]
        public int ChannelID
        {
            get { return _ChannelID; }
            set
            {
                _ChannelID = value;
                MarkColumnModified("ChannelID");
            }
        }

        private int _ChannelID;

        [Column]
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set
            {
                _CreatedOn = value;
                MarkColumnModified("CreatedOn");
            }
        }

        private DateTime _CreatedOn;

        [Column]
        public int ID
        {
            get { return _ID; }
            set
            {
                _ID = value;
                MarkColumnModified("ID");
            }
        }

        private int _ID;

        [Column]
        public bool IsActive
        {
            get { return _IsActive; }
            set
            {
                _IsActive = value;
                MarkColumnModified("IsActive");
            }
        }

        private bool _IsActive;

        [Column]
        public long KeyEntryID
        {
            get { return _KeyEntryID; }
            set
            {
                _KeyEntryID = value;
                MarkColumnModified("KeyEntryID");
            }
        }

        private long _KeyEntryID;

        [Column]
        public int? KeyIndex
        {
            get { return _KeyIndex; }
            set
            {
                _KeyIndex = value;
                MarkColumnModified("KeyIndex");
            }
        }

        private int? _KeyIndex;

        [Column]
        public int? KeyUsage
        {
            get { return _KeyUsage; }
            set
            {
                _KeyUsage = value;
                MarkColumnModified("KeyUsage");
            }
        }

        private int? _KeyUsage;

        [Column]
        public DateTime? ModifiedOn
        {
            get { return _ModifiedOn; }
            set
            {
                _ModifiedOn = value;
                MarkColumnModified("ModifiedOn");
            }
        }

        private DateTime? _ModifiedOn;

        [Column]
        public long? OldKeyEntryID
        {
            get { return _OldKeyEntryID; }
            set
            {
                _OldKeyEntryID = value;
                MarkColumnModified("OldKeyEntryID");
            }
        }

        private long? _OldKeyEntryID;

        [Column]
        public string Title
        {
            get { return _Title; }
            set
            {
                _Title = value;
                MarkColumnModified("Title");
            }
        }

        private string _Title;

    }

    [TableName("[dbo].[CfgKeyTable]")]
    [PrimaryKey("ID")]
    [ExplicitColumns]
    public partial class CfgKeyTable
        : Record<CfgKeyTable>
    {
        [Column]
        public DateTime? CreatedOn
        {
            get { return _CreatedOn; }
            set
            {
                _CreatedOn = value;
                MarkColumnModified("CreatedOn");
            }
        }

        private DateTime? _CreatedOn;

        [Column]
        public int? EncKeyID
        {
            get { return _EncKeyID; }
            set
            {
                _EncKeyID = value;
                MarkColumnModified("EncKeyID");
            }
        }

        private int? _EncKeyID;

        [Column]
        public int ID
        {
            get { return _ID; }
            set
            {
                _ID = value;
                MarkColumnModified("ID");
            }
        }

        private int _ID;

        [Column]
        public string KeyTitle
        {
            get { return _KeyTitle; }
            set
            {
                _KeyTitle = value;
                MarkColumnModified("KeyTitle");
            }
        }

        private string _KeyTitle;

        [Column]
        public int? KeyType
        {
            get { return _KeyType; }
            set
            {
                _KeyType = value;
                MarkColumnModified("KeyType");
            }
        }

        private int? _KeyType;

        [Column]
        public int? KeyUsage
        {
            get { return _KeyUsage; }
            set
            {
                _KeyUsage = value;
                MarkColumnModified("KeyUsage");
            }
        }

        private int? _KeyUsage;

        [Column]
        public string KeyVal
        {
            get { return _KeyVal; }
            set
            {
                _KeyVal = value;
                MarkColumnModified("KeyVal");
            }
        }

        private string _KeyVal;

        [Column]
        public string KVC
        {
            get { return _KVC; }
            set
            {
                _KVC = value;
                MarkColumnModified("KVC");
            }
        }

        private string _KVC;

        [Column]
        public string LKVC
        {
            get { return _LKVC; }
            set
            {
                _LKVC = value;
                MarkColumnModified("LKVC");
            }
        }

        private string _LKVC;

    }

    [TableName("[dbo].[Core_ChannelKeyStore]")]
    [PrimaryKey("Id")]
    [ExplicitColumns]
    public partial class Core_ChannelKeyStore
        : Record<Core_ChannelKeyStore>
    {
        [Column]
        public int? ChannelID
        {
            get { return _ChannelID; }
            set
            {
                _ChannelID = value;
                MarkColumnModified("ChannelID");
            }
        }

        private int? _ChannelID;

        [Column]
        public string CreatedBy
        {
            get { return _CreatedBy; }
            set
            {
                _CreatedBy = value;
                MarkColumnModified("CreatedBy");
            }
        }

        private string _CreatedBy;

        [Column]
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set
            {
                _CreatedOn = value;
                MarkColumnModified("CreatedOn");
            }
        }

        private DateTime _CreatedOn;

        [Column]
        public int Id
        {
            get { return _Id; }
            set
            {
                _Id = value;
                MarkColumnModified("Id");
            }
        }

        private int _Id;

        [Column]
        public bool IsActive
        {
            get { return _IsActive; }
            set
            {
                _IsActive = value;
                MarkColumnModified("IsActive");
            }
        }

        private bool _IsActive;

        [Column]
        public int? KeyId
        {
            get { return _KeyId; }
            set
            {
                _KeyId = value;
                MarkColumnModified("KeyId");
            }
        }

        private int? _KeyId;

        [Column]
        public int? KeyIndex
        {
            get { return _KeyIndex; }
            set
            {
                _KeyIndex = value;
                MarkColumnModified("KeyIndex");
            }
        }

        private int? _KeyIndex;

        [Column]
        public int? KeyType
        {
            get { return _KeyType; }
            set
            {
                _KeyType = value;
                MarkColumnModified("KeyType");
            }
        }

        private int? _KeyType;

        [Column]
        public string ModifiedBy
        {
            get { return _ModifiedBy; }
            set
            {
                _ModifiedBy = value;
                MarkColumnModified("ModifiedBy");
            }
        }

        private string _ModifiedBy;

        [Column]
        public DateTime? ModifiedOn
        {
            get { return _ModifiedOn; }
            set
            {
                _ModifiedOn = value;
                MarkColumnModified("ModifiedOn");
            }
        }

        private DateTime? _ModifiedOn;

        [Column]
        public int? OldKeyID
        {
            get { return _OldKeyID; }
            set
            {
                _OldKeyID = value;
                MarkColumnModified("OldKeyID");
            }
        }

        private int? _OldKeyID;

        [Column]
        public int SwitchId
        {
            get { return _SwitchId; }
            set
            {
                _SwitchId = value;
                MarkColumnModified("SwitchId");
            }
        }

        private int _SwitchId;

    }

    [TableName("[dbo].[Core_Channels]")]
    [ExplicitColumns]
    public partial class Core_Channel
        : Record<Core_Channel>
    {
        [Column]
        public long? ChannelAccountID
        {
            get { return _ChannelAccountID; }
            set
            {
                _ChannelAccountID = value;
                MarkColumnModified("ChannelAccountID");
            }
        }

        private long? _ChannelAccountID;

        [Column]
        public string ChannelName
        {
            get { return _ChannelName; }
            set
            {
                _ChannelName = value;
                MarkColumnModified("ChannelName");
            }
        }

        private string _ChannelName;

        [Column]
        public string CreatedBy
        {
            get { return _CreatedBy; }
            set
            {
                _CreatedBy = value;
                MarkColumnModified("CreatedBy");
            }
        }

        private string _CreatedBy;

        [Column]
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set
            {
                _CreatedOn = value;
                MarkColumnModified("CreatedOn");
            }
        }

        private DateTime _CreatedOn;

        [Column]
        public int? EncryptionModelCode
        {
            get { return _EncryptionModelCode; }
            set
            {
                _EncryptionModelCode = value;
                MarkColumnModified("EncryptionModelCode");
            }
        }

        private int? _EncryptionModelCode;

        [Column]
        public string FwIIN
        {
            get { return _FwIIN; }
            set
            {
                _FwIIN = value;
                MarkColumnModified("FwIIN");
            }
        }

        private string _FwIIN;

        [Column]
        public int Id
        {
            get { return _Id; }
            set
            {
                _Id = value;
                MarkColumnModified("Id");
            }
        }

        private int _Id;

        [Column]
        public bool JournalEnable
        {
            get { return _JournalEnable; }
            set
            {
                _JournalEnable = value;
                MarkColumnModified("JournalEnable");
            }
        }

        private bool _JournalEnable;

        [Column]
        public int? KeyCount
        {
            get { return _KeyCount; }
            set
            {
                _KeyCount = value;
                MarkColumnModified("KeyCount");
            }
        }

        private int? _KeyCount;

        [Column]
        public int? KeyType
        {
            get { return _KeyType; }
            set
            {
                _KeyType = value;
                MarkColumnModified("KeyType");
            }
        }

        private int? _KeyType;

        [Column]
        public int? MasterZoneKeyId
        {
            get { return _MasterZoneKeyId; }
            set
            {
                _MasterZoneKeyId = value;
                MarkColumnModified("MasterZoneKeyId");
            }
        }

        private int? _MasterZoneKeyId;

        [Column]
        public string ModifiedBy
        {
            get { return _ModifiedBy; }
            set
            {
                _ModifiedBy = value;
                MarkColumnModified("ModifiedBy");
            }
        }

        private string _ModifiedBy;

        [Column]
        public DateTime ModifiedOn
        {
            get { return _ModifiedOn; }
            set
            {
                _ModifiedOn = value;
                MarkColumnModified("ModifiedOn");
            }
        }

        private DateTime _ModifiedOn;

        [Column]
        public int? RRNEntityID
        {
            get { return _RRNEntityID; }
            set
            {
                _RRNEntityID = value;
                MarkColumnModified("RRNEntityID");
            }
        }

        private int? _RRNEntityID;

        [Column]
        public bool SettlementEnable
        {
            get { return _SettlementEnable; }
            set
            {
                _SettlementEnable = value;
                MarkColumnModified("SettlementEnable");
            }
        }

        private bool _SettlementEnable;

        [Column]
        public bool ShaparakEnable
        {
            get { return _ShaparakEnable; }
            set
            {
                _ShaparakEnable = value;
                MarkColumnModified("ShaparakEnable");
            }
        }

        private bool _ShaparakEnable;

        [Column]
        public int? SubLedgerIdentifier
        {
            get { return _SubLedgerIdentifier; }
            set
            {
                _SubLedgerIdentifier = value;
                MarkColumnModified("SubLedgerIdentifier");
            }
        }

        private int? _SubLedgerIdentifier;

        [Column]
        public bool SwitchChannel
        {
            get { return _SwitchChannel; }
            set
            {
                _SwitchChannel = value;
                MarkColumnModified("SwitchChannel");
            }
        }

        private bool _SwitchChannel;

        [Column]
        public int? SwitchId
        {
            get { return _SwitchId; }
            set
            {
                _SwitchId = value;
                MarkColumnModified("SwitchId");
            }
        }

        private int? _SwitchId;

        [Column]
        public long? WagePartyBankAccountID
        {
            get { return _WagePartyBankAccountID; }
            set
            {
                _WagePartyBankAccountID = value;
                MarkColumnModified("WagePartyBankAccountID");
            }
        }

        private long? _WagePartyBankAccountID;

    }

    [TableName("[dbo].[CT_ChannelConfig]")]
    [ExplicitColumns]
    public partial class CT_ChannelConfig
        : Record<CT_ChannelConfig>
    {
        [Column]
        public string ChannelName
        {
            get { return _ChannelName; }
            set
            {
                _ChannelName = value;
                MarkColumnModified("ChannelName");
            }
        }

        private string _ChannelName;

        [Column]
        public int CurrentTraceNo
        {
            get { return _CurrentTraceNo; }
            set
            {
                _CurrentTraceNo = value;
                MarkColumnModified("CurrentTraceNo");
            }
        }

        private int _CurrentTraceNo;

    }

    [TableName("[dbo].[CT_TermState]")]
    [PrimaryKey("ID")]
    [ExplicitColumns]
    public partial class CT_TermState
        : Record<CT_TermState>
    {
        [Column]
        public bool ChangeKeyAllowed
        {
            get { return _ChangeKeyAllowed; }
            set
            {
                _ChangeKeyAllowed = value;
                MarkColumnModified("ChangeKeyAllowed");
            }
        }

        private bool _ChangeKeyAllowed;

        [Column]
        public int? CKey1
        {
            get { return _CKey1; }
            set
            {
                _CKey1 = value;
                MarkColumnModified("CKey1");
            }
        }

        private int? _CKey1;

        [Column]
        public int? CKey2
        {
            get { return _CKey2; }
            set
            {
                _CKey2 = value;
                MarkColumnModified("CKey2");
            }
        }

        private int? _CKey2;

        [Column]
        public int? CKey3
        {
            get { return _CKey3; }
            set
            {
                _CKey3 = value;
                MarkColumnModified("CKey3");
            }
        }

        private int? _CKey3;

        [Column]
        public string CreatedBy
        {
            get { return _CreatedBy; }
            set
            {
                _CreatedBy = value;
                MarkColumnModified("CreatedBy");
            }
        }

        private string _CreatedBy;

        [Column]
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set
            {
                _CreatedOn = value;
                MarkColumnModified("CreatedOn");
            }
        }

        private DateTime _CreatedOn;

        [Column]
        public long ID
        {
            get { return _ID; }
            set
            {
                _ID = value;
                MarkColumnModified("ID");
            }
        }

        private long _ID;

        [Column]
        public bool IsConfigAllowed
        {
            get { return _IsConfigAllowed; }
            set
            {
                _IsConfigAllowed = value;
                MarkColumnModified("IsConfigAllowed");
            }
        }

        private bool _IsConfigAllowed;

        [Column]
        public int KeyType
        {
            get { return _KeyType; }
            set
            {
                _KeyType = value;
                MarkColumnModified("KeyType");
            }
        }

        private int _KeyType;

        [Column]
        public string ModifiedBy
        {
            get { return _ModifiedBy; }
            set
            {
                _ModifiedBy = value;
                MarkColumnModified("ModifiedBy");
            }
        }

        private string _ModifiedBy;

        [Column]
        public DateTime? ModifiedOn
        {
            get { return _ModifiedOn; }
            set
            {
                _ModifiedOn = value;
                MarkColumnModified("ModifiedOn");
            }
        }

        private DateTime? _ModifiedOn;

        [Column]
        public int? OKey1
        {
            get { return _OKey1; }
            set
            {
                _OKey1 = value;
                MarkColumnModified("OKey1");
            }
        }

        private int? _OKey1;

        [Column]
        public int? OKey2
        {
            get { return _OKey2; }
            set
            {
                _OKey2 = value;
                MarkColumnModified("OKey2");
            }
        }

        private int? _OKey2;

        [Column]
        public int? OKey3
        {
            get { return _OKey3; }
            set
            {
                _OKey3 = value;
                MarkColumnModified("OKey3");
            }
        }

        private int? _OKey3;

        [Column]
        public int Status
        {
            get { return _Status; }
            set
            {
                _Status = value;
                MarkColumnModified("Status");
            }
        }

        private int _Status;

        [Column]
        public int SwitchID
        {
            get { return _SwitchID; }
            set
            {
                _SwitchID = value;
                MarkColumnModified("SwitchID");
            }
        }

        private int _SwitchID;

        [Column]
        public int TermID
        {
            get { return _TermID; }
            set
            {
                _TermID = value;
                MarkColumnModified("TermID");
            }
        }

        private int _TermID;

    }

    [TableName("[dbo].[KeyStore]")]
    [PrimaryKey("KeyId")]
    [ExplicitColumns]
    public partial class KeyStore
        : Record<KeyStore>
    {
        [Column]
        public string CreatedBy
        {
            get { return _CreatedBy; }
            set
            {
                _CreatedBy = value;
                MarkColumnModified("CreatedBy");
            }
        }

        private string _CreatedBy;

        [Column]
        public DateTime? CreatedOn
        {
            get { return _CreatedOn; }
            set
            {
                _CreatedOn = value;
                MarkColumnModified("CreatedOn");
            }
        }

        private DateTime? _CreatedOn;

        [Column]
        public int EncKeyId
        {
            get { return _EncKeyId; }
            set
            {
                _EncKeyId = value;
                MarkColumnModified("EncKeyId");
            }
        }

        private int _EncKeyId;

        [Column]
        public int? EncModel
        {
            get { return _EncModel; }
            set
            {
                _EncModel = value;
                MarkColumnModified("EncModel");
            }
        }

        private int? _EncModel;

        [Column]
        public int KeyId
        {
            get { return _KeyId; }
            set
            {
                _KeyId = value;
                MarkColumnModified("KeyId");
            }
        }

        private int _KeyId;

        [Column]
        public int KeyTypeId
        {
            get { return _KeyTypeId; }
            set
            {
                _KeyTypeId = value;
                MarkColumnModified("KeyTypeId");
            }
        }

        private int _KeyTypeId;

        [Column]
        public string KeyValue1
        {
            get { return _KeyValue1; }
            set
            {
                _KeyValue1 = value;
                MarkColumnModified("KeyValue1");
            }
        }

        private string _KeyValue1;

        [Column]
        public string KVC
        {
            get { return _KVC; }
            set
            {
                _KVC = value;
                MarkColumnModified("KVC");
            }
        }

        private string _KVC;

        [Column]
        public int? SwitchId
        {
            get { return _SwitchId; }
            set
            {
                _SwitchId = value;
                MarkColumnModified("SwitchId");
            }
        }

        private int? _SwitchId;

        [Column]
        public string Title
        {
            get { return _Title; }
            set
            {
                _Title = value;
                MarkColumnModified("Title");
            }
        }

        private string _Title;

    }

    [TableName("[dbo].[VwSepTransactions]")]
    [ExplicitColumns]
    public partial class VwSepTransaction
        : Record<VwSepTransaction>
    {
        [Column]
        public int? AffectiveAmount
        {
            get { return _AffectiveAmount; }
            set
            {
                _AffectiveAmount = value;
                MarkColumnModified("AffectiveAmount");
            }
        }

        private int? _AffectiveAmount;

        [Column]
        public int? CallerAddress
        {
            get { return _CallerAddress; }
            set
            {
                _CallerAddress = value;
                MarkColumnModified("CallerAddress");
            }
        }

        private int? _CallerAddress;

        [Column]
        public int? CreatedOn
        {
            get { return _CreatedOn; }
            set
            {
                _CreatedOn = value;
                MarkColumnModified("CreatedOn");
            }
        }

        private int? _CreatedOn;

        [Column]
        public int? CustomerAddress
        {
            get { return _CustomerAddress; }
            set
            {
                _CustomerAddress = value;
                MarkColumnModified("CustomerAddress");
            }
        }

        private int? _CustomerAddress;

        [Column]
        public int? functionCode
        {
            get { return _functionCode; }
            set
            {
                _functionCode = value;
                MarkColumnModified("functionCode");
            }
        }

        private int? _functionCode;

        [Column]
        public int? Id
        {
            get { return _Id; }
            set
            {
                _Id = value;
                MarkColumnModified("Id");
            }
        }

        private int? _Id;

        [Column]
        public int? mAddData
        {
            get { return _mAddData; }
            set
            {
                _mAddData = value;
                MarkColumnModified("mAddData");
            }
        }

        private int? _mAddData;

        [Column]
        public int? MerchantName
        {
            get { return _MerchantName; }
            set
            {
                _MerchantName = value;
                MarkColumnModified("MerchantName");
            }
        }

        private int? _MerchantName;

        [Column]
        public int? ModifiedOn
        {
            get { return _ModifiedOn; }
            set
            {
                _ModifiedOn = value;
                MarkColumnModified("ModifiedOn");
            }
        }

        private int? _ModifiedOn;

        [Column]
        public int? MTI
        {
            get { return _MTI; }
            set
            {
                _MTI = value;
                MarkColumnModified("MTI");
            }
        }

        private int? _MTI;

        [Column]
        public int? OriginalAmount
        {
            get { return _OriginalAmount; }
            set
            {
                _OriginalAmount = value;
                MarkColumnModified("OriginalAmount");
            }
        }

        private int? _OriginalAmount;

        [Column]
        public int? Pan
        {
            get { return _Pan; }
            set
            {
                _Pan = value;
                MarkColumnModified("Pan");
            }
        }

        private int? _Pan;

        [Column]
        public int? PAN1
        {
            get { return _PAN1; }
            set
            {
                _PAN1 = value;
                MarkColumnModified("PAN1");
            }
        }

        private int? _PAN1;

        [Column]
        public int? PosCondtion
        {
            get { return _PosCondtion; }
            set
            {
                _PosCondtion = value;
                MarkColumnModified("PosCondtion");
            }
        }

        private int? _PosCondtion;

        [Column]
        public int? PrCode
        {
            get { return _PrCode; }
            set
            {
                _PrCode = value;
                MarkColumnModified("PrCode");
            }
        }

        private int? _PrCode;

        [Column]
        public int? PTraceDt
        {
            get { return _PTraceDt; }
            set
            {
                _PTraceDt = value;
                MarkColumnModified("PTraceDt");
            }
        }

        private int? _PTraceDt;

        [Column]
        public int? PTraceNo
        {
            get { return _PTraceNo; }
            set
            {
                _PTraceNo = value;
                MarkColumnModified("PTraceNo");
            }
        }

        private int? _PTraceNo;

        [Column]
        public int? RefrenceNumber
        {
            get { return _RefrenceNumber; }
            set
            {
                _RefrenceNumber = value;
                MarkColumnModified("RefrenceNumber");
            }
        }

        private int? _RefrenceNumber;

        [Column]
        public int? ResNum
        {
            get { return _ResNum; }
            set
            {
                _ResNum = value;
                MarkColumnModified("ResNum");
            }
        }

        private int? _ResNum;

        [Column]
        public int? ResNum1
        {
            get { return _ResNum1; }
            set
            {
                _ResNum1 = value;
                MarkColumnModified("ResNum1");
            }
        }

        private int? _ResNum1;

        [Column]
        public int? ResNum2
        {
            get { return _ResNum2; }
            set
            {
                _ResNum2 = value;
                MarkColumnModified("ResNum2");
            }
        }

        private int? _ResNum2;

        [Column]
        public int? ResNum3
        {
            get { return _ResNum3; }
            set
            {
                _ResNum3 = value;
                MarkColumnModified("ResNum3");
            }
        }

        private int? _ResNum3;

        [Column]
        public int? ResNum4
        {
            get { return _ResNum4; }
            set
            {
                _ResNum4 = value;
                MarkColumnModified("ResNum4");
            }
        }

        private int? _ResNum4;

        [Column]
        public int? ResponseCode
        {
            get { return _ResponseCode; }
            set
            {
                _ResponseCode = value;
                MarkColumnModified("ResponseCode");
            }
        }

        private int? _ResponseCode;

        [Column]
        public int? ReverseStatusCode
        {
            get { return _ReverseStatusCode; }
            set
            {
                _ReverseStatusCode = value;
                MarkColumnModified("ReverseStatusCode");
            }
        }

        private int? _ReverseStatusCode;

        [Column]
        public int? ReverseTime
        {
            get { return _ReverseTime; }
            set
            {
                _ReverseTime = value;
                MarkColumnModified("ReverseTime");
            }
        }

        private int? _ReverseTime;

        [Column]
        public int? RRN
        {
            get { return _RRN; }
            set
            {
                _RRN = value;
                MarkColumnModified("RRN");
            }
        }

        private int? _RRN;

        [Column]
        public int? SettlementStatus
        {
            get { return _SettlementStatus; }
            set
            {
                _SettlementStatus = value;
                MarkColumnModified("SettlementStatus");
            }
        }

        private int? _SettlementStatus;

        [Column]
        public int? STraceDt
        {
            get { return _STraceDt; }
            set
            {
                _STraceDt = value;
                MarkColumnModified("STraceDt");
            }
        }

        private int? _STraceDt;

        [Column]
        public int? STraceNo
        {
            get { return _STraceNo; }
            set
            {
                _STraceNo = value;
                MarkColumnModified("STraceNo");
            }
        }

        private int? _STraceNo;

        [Column]
        public int? SwitchId
        {
            get { return _SwitchId; }
            set
            {
                _SwitchId = value;
                MarkColumnModified("SwitchId");
            }
        }

        private int? _SwitchId;

        [Column]
        public int? TermId
        {
            get { return _TermId; }
            set
            {
                _TermId = value;
                MarkColumnModified("TermId");
            }
        }

        private int? _TermId;

        [Column]
        public int? Track2
        {
            get { return _Track2; }
            set
            {
                _Track2 = value;
                MarkColumnModified("Track2");
            }
        }

        private int? _Track2;

        [Column]
        public int? TrStatus
        {
            get { return _TrStatus; }
            set
            {
                _TrStatus = value;
                MarkColumnModified("TrStatus");
            }
        }

        private int? _TrStatus;

    }

}

